apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pod.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.pod.name }}
          image: {{ .Values.pod.image }}
          imagePullPolicy: {{ .Values.pod.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.pod.port }}
