# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  # Tokyonight Moon
  theme:
    activeBorderColor:
      - "#ff966c"
      - "bold"
    cherryPickedCommitBgColor:
      - "#c099ff"
    cherryPickedCommitFgColor:
      - "#82aaff"
    defaultFgColor:
      - "#c8d3f5"
    inactiveBorderColor:
      - "#589ed7"
    optionsTextColor:
      - "#82aaff"
    searchingActiveBorderColor:
      - "#ff966c"
      - "bold"
    selectedLineBgColor:
      - "#2d3f76"
    unstagedChangesColor:
      - "#c53b53"
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
git:
  overrideGpg: true # prevents lazygit from spawning a separate process when using GPG
os:
  editPreset: "nvim" # nvim-remote works so-so
