monitor = , preferred, auto, 1

$terminal = foot
$mod = SUPER

exec-once = quickshell

bind = $mod, Return, exec, $terminal
bind = $mod, Q, killactive
bind = $mod SHIFT, E, exit

general {
  gaps_in = 4
  gaps_out = 8
  border_size = 2
}

decoration {
  rounding = 8
}

# virtio-gpu has no cursor plane
cursor {
  no_hardware_cursors = true
}

ecosystem {
  no_update_news = true
  no_donation_nag = true
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  force_default_wallpaper = 0
}
