# Usage:
# brew bundle --file=path/to/Brewfile

# Manually install cask-app using: brew install --cask xxx --appdir /Applications
cask_args appdir: '/Applications'

# Taps (third-party repositories)
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'cantino/mcfly'

# CLIs
brew 'asciinema'
brew 'pre-commit'
brew 'tree'
brew 'pgcli'
brew 'mcfly'
brew 'exa'
brew 'bat'
brew 'withgraphite/tap/graphite'
brew 'kubectx'

# LazyVim
brew 'ripgrep'
brew 'fd'
brew 'lazygit'

# GUIs
cask 'appcleaner'
cask 'rectangle'
cask 'spotify'
cask 'visual-studio-code'
# cask 'kitty'
# cask 'alacritty'
cask 'karabiner-elements'
