# Usage:
# brew bundle --file=path/to/Brewfile

# Manually install cask-app using: brew install --cask xxx --appdir /Applications
cask_args appdir: '/Applications'

# Taps (third-party repositories)
tap 'homebrew/bundle'
tap 'homebrew/core'

# CLIs
brew 'asciinema'
brew 'pre-commit'
brew 'tree'
brew 'pgcli'

# CLIs but weirdly enough, a Cask
cask 'miniforge'

# GUIs
cask 'appcleaner'
cask 'rectangle'
cask 'docker'
cask 'spotify'
cask 'visual-studio-code'
