[[language]]
# Info: https://github.com/helix-editor/helix/discussions/4689#discussioncomment-4103641
name = "python"
rulers = [72, 88]
scope = "source.python"
injection-regex = "python"
file-types = ["py"]
shebangs = ["python"]
roots = ["pyproject.toml", "poetry.lock", "requirement.txt", "setup.py"]
comment-token = "#"
language-server = { command = "pyright-langserver", args = ["--stdio"] }  # setup via: pipx install pyright
indent = { tab-width = 4, unit = "    " }
config = {}  # TODO: https://github.com/helix-editor/helix/issues/1898
auto-format = true
formatter = { command = "sh", args = ["-c", "black --quiet - | isort -"]}  # Format with black, sort imports with isort
