# SOPS configuration for rpi5-homelab secrets
# This file specifies which keys can decrypt the secrets

keys:
  # SSH public key converted to age format
  # To get your age public key: ssh-to-age < ~/.ssh/id_ed25519.pub
  - &fredrik_ssh age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
    - age:
      - *fredrik_ssh