services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${JELLYFIN_UID}:${JELLYFIN_GID}
    network_mode: 'host'
    volumes:
      - ${JELLYFIN_CONFIG_LOCATION}:/config
      - ${JELLYFIN_CACHE_LOCATION}:/cache
      - type: bind
        source: ${JELLYFIN_MEDIA_LOCATION}
        target: /media
        read_only: true
      # Optional - extra fonts for subtitle burn-in during transcoding
      - type: bind
        source: /usr/share/fonts
        target: /usr/local/share/fonts/custom
        read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHED_SERVER_URL}
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # Optional: Enable hardware acceleration for Raspberry Pi
    # Uncomment the following lines if you want GPU acceleration
    # devices:
    #   - /dev/dri:/dev/dri