version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"   # TCP tunnel server for Edge agents (optional)
      - "9000:9000"   # HTTP port (legacy/optional)
      - "9443:9443"   # HTTPS port (primary)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
    driver: local