# https://github.com/dlvhdr/gh-dash#%EF%B8%8F-configuring

prSections:
  - title: Mine
    filters: sort:updated-desc is:pr is:open archived:false user:@me
  - title: Dependabot
    filters: is:open -org:einride review-requested:@me author:app/dependabot archived:false
  - title: Created @einride
    filters: is:open author:@me org:einride archived:false
  - title: Review requested @einride
    filters: is:open review-requested:@me -author:app/dependabot org:einride archived:false
  - title: Dependabot @einride
    filters: is:open org:einride review-requested:@me author:app/dependabot archived:false
issuesSections:
  - title: Mine
    filters: sort:updated-desc is:issue is:open archived:false user:@me
  - title: Created
    filters: sort:updated-desc is:open is:issue archived:false author:fredrikaverpil
  - title: Assigned
    filters: sort:updated-desc is:open is:issue archived:false assignee:fredrikaverpil
  - title: Mentioned
    filters: sort:updated-desc is:open is:issue archived:false mentions:fredrikaverpil
  - title: Involved
    filters: sort:updated-desc is:issue is:open archived:false involves:@me
defaults:
  refetchIntervalMinutes: 5
