# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-37ba1a0f-4a93-4d3b-bceb-cf80cc75af6b";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-37ba1a0f-4a93-4d3b-bceb-cf80cc75af6b".device =
    "/dev/disk/by-uuid/37ba1a0f-4a93-4d3b-bceb-cf80cc75af6b";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C850-39D4";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-2bc8d428-9495-4fd8-aaba-9208e0bbaf0f"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
