apiVersion: v1
kind: Pod
metadata:
  name: gohello-pod
  namespace: gohello
spec:
  containers:
    - name: gohello-container
      image: docker.io/fredrikaverpil/gohello:0.0.1
      ports:
        - containerPort: 9090
          hostPort: 8080
