apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.pod.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  containers:
    - name: {{ .Values.pod.name }}
      image: {{ .Values.pod.image }}
      ports:
        - containerPort: {{ .Values.pod.port }}

