name: CI
on:
  # push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create workfolder
        run: |
          mkdir -p ~/dotfiles-install-dir

      - name: Install dotfiles
        run: |
          HOME=~/dotfiles-install-dir ./install -vv

      - name: Show dotfiles
        run: |
          ls -alh ~/dotfiles-install-dir

      - name: Test Python installation
        run: |
          PATH=~/dotfiles-install-dir/.pyenv/bin/:$PATH
          HOME=~/dotfiles-install-dir eval "$(pyenv init --path)"
          HOME=~/dotfiles-install-dir pyenv local 3.9.7
          HOME=~/dotfiles-install-dir python -c "import sys; assert sys.version.startswith('3.9.7')"
          HOME=~/dotfiles-install-dir pipx install poetry
          HOME=~/dotfiles-install-dir poetry --version

      - name: Test Docker installation
        run: |
          installers/docker.sh
          sudo docker run hello-world

      # - name: Test snap apps install
      #   run: |
      #     installers/snap-apps.sh
