name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create workfolder
        run: |
          mkdir -p ~/dotfiles-install-dir

      - name: Install dotfiles
        run: |
          HOME=~/dotfiles-install-dir ./install -vv

      - name: Show dotfiles
        run: |
          ls -alh ~/dotfiles-install-dir

      - name: Test Python install via pyenv
        run: |
          HOME=~/dotfiles-install-dir ~/dotfiles-install-dir/.pyenv/bin/pyenv install 3.9.7
  
      - name: Test snap apps install
        run: |
          pwd
          ls -alh
          installers/snap-apps.sh
