name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create workfolder
        run: |
          mkdir -p ~/dotfiles-install-dir

      - name: Install dotfiles
        run: |
          HOME=~/dotfiles-install-dir ./install -vv

      - name: Show dotfiles
        run: |
          ls -alh ~/dotfiles-install-dir

      - name: Test Python setup
        run: |
          echo $PYENV_ROOT
          echo "$PYENV_ROOT/shims:$PYENV_ROOT/bin" >> $GITHUB_PATH
          HOME=~/dotfiles-install-dir installers/python.sh

          # Test Pyenv-installed Python version
          python -c "import sys; print(sys.version)"
          python -c "import sys; assert sys.version.startswith('${BASE_PYTHON_VER}')"

          # Test Pipx
          /usr/bin/pipx list
          poetry --version
          black --version
          ipython --version

        env:
          PYENV_ROOT: /home/runner/dotfiles-install-dir/.pyenv


      - name: Test Docker setup
        run: |
          installers/docker.sh
          sudo docker run hello-world

      # - name: Test snap apps setup
      #   run: |
      #     installers/snap-apps.sh
