name: CI

on:
  # push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create workfolder
        run: |
          mkdir -p ~/dotfiles-install-dir

      - name: Install dotfiles
        run: |
          HOME=~/dotfiles-install-dir ./install -vv

      - name: Show dotfiles
        run: |
          ls -alh ~/dotfiles-install-dir

      - name: Test Python setup
        run: |
          BASE_PYTHON_VER=`cat .python-version`
          # Add Pyenv to PATH
          echo "$PYENV_ROOT/bin" >> $GITHUB_PATH

          # Test Python via pyenv
          eval "$($HOME/dotfiles-install-dir/.pyenv/bin/pyenv init --path)"
          python -c "import sys; print(sys.version)"
          python -c "import sys; assert sys.version.startswith('${BASE_PYTHON_VER}')"

          # Test Poetry via Pipx
          pipx install poetry
          pipx runpip poetry list
          poetry --version

        env:
          PYENV_ROOT: $HOME/dotfiles-install-dir/.pyenv

      - name: Test Docker setup
        run: |
          installers/docker.sh
          sudo docker run hello-world

      # - name: Test snap apps setup
      #   run: |
      #     installers/snap-apps.sh
