name: CI

on:
  # push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create workfolder
        run: |
          mkdir -p ~/dotfiles-install-dir

      - name: Install dotfiles
        run: |
          HOME=~/dotfiles-install-dir ./install -vv

      - name: Show dotfiles
        run: |
          ls -alh ~/dotfiles-install-dir

      - name: Test Python installation
        run: |
          pwd
          ls -alh
          # ls -alh $HOME/dotfiles-install-dir/.pyenv


          # Add Pyenv to PATH
          # echo "$HOME/dotfiles-install-dir/.pyenv/bin" >> $GITHUB_PATH


          eval "$($HOME/dotfiles-install-dir/.pyenv/bin/pyenv init --path)"
          # $HOME/dotfiles-install-dir/.pyenv/bin/pyenv local 3.9.7
          $HOME/dotfiles-install-dir/.pyenv/bin/pyenv versions


          # python -c "import sys; assert sys.version.startswith('3.9.7')"

        # env:
        #   HOME: /home/runner/dotfiles/dotfiles-install-dir/

      # - name: Test Docker installation
      #   run: |
      #     installers/docker.sh
      #     sudo docker run hello-world

      # - name: Test snap apps install
      #   run: |
      #     installers/snap-apps.sh
